version: '3.3'
services:
  # Deploy MariaDB as database for API
  database:
    image: mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=DevOpsdb
      - MARIADB_ROOT_PASSWORD=root

  # Deploy phpmyadmin to view the database
  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database

  # Deploy NestJS Rest API
  api:
    image: zettee/devops-api:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_PASS=root
      - DB_USER=root
      - DB_NAME=DevOpsdb

  # Deploy Angular application
  app:
    image: zettee/devops-app:latest
    restart: unless-stopped
    pull_policy: always
    depends_on:
      - api
    ports:
      - "8888:80"
    environment:
      - API_HOSTNAME=api
   
  
