version: '3.9'
services:
  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: DevOpsdb
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=database
